
```{r echo=FALSE, results=hide}
## DATA GENERATION
sen <- 800 / 850
spe <- 0.9
pre <- 850 / (850 + 9150)
## QUESTION/ANSWER GENERATION
tp <- pre * sen
fn <- pre * (1-sen)
fp <- (1-pre) * (1-spe)
tn <- (1-pre) * spe
ppv <- tp / (tp + fp)
npv <- tn / (tn + fn)
```

Question
========
A test to detect the COVID19 was applied to 850 persons infected by COVID19 with a positive outcome in 800 of them, and it was also applied to 9150 non-infected persons with a positive outcome in 10%: of them.
a. Compute the sensitivity and the specificity of the test.
a. Compute the positive and the negative predictive values and interpret them. 
a. Compute the probability of a correct diagnostic.

Solution
========
Let $D$ the event corresponding to suffering COVID19 and $+$ and $-$ the events corresponding to get a positive and a negative outcome respectively.
a. The sensitivity is $P(+|D) = `r round(sen, 4)`$ and specificity $P(-|\overline D) = `r round(spe, 4)`$.
a. Positive predictive value $P(D|+) = `r round(ppv, 4)`$ and negative predictive value $P(\overline D|-) = `r round(npv, 4)`$. As de positive predictive value is less than 0.5 we can not use this test to confirm COVID19, but we can use it to rule it out with a strong confidence since the negative predictive value is pretty close to 1. 
a. $P(D\cap +) + P(\overline D\cap -) = `r round(tp + tn, 4)`$.

Meta-information 
================
extype: num
exsolution: Solution
exname: test-med-4
extol: 0.001
degree: Medicine
 
  
