<<echo=FALSE, results=hide>>=
## DATA GENERATION
ppv <- 0.4
npv <- 0.95
pre <- 0.1
## QUESTION/ANSWER GENERATION
tp <- 0.0571
fp <- 0.0857
fn <- 0.0429
tn <- 0.8143
sen <- tp / (tp + fn)
spe <- tn / (fp + tn)
minspe <- 0.857
@

\begin{question}
\puntos{3}A diagnostic test for a disease with a prevalence of 10\% has a positive predictive value of 40\% and negative predictive value of 95\%. 
\begin{enumerate}
\item Compute the sensitivity and the specificity of the test.
\item Compute the probability of a right diagnose.
\item What must be the minimum sensitivity of the test to be able to diagnose the disease? 
\end{enumerate}
\end{question}

%% SOLUTIONS
\begin{solution}
\begin{enumerate}
\item Sensitivity $P(+|D)=\Sexpr{round(sen, 4)}$ and specificity $P(-|\overline D)=\Sexpr{round(spe, 4)}$.
\item $P(\mbox{Right diagnose}) = P(D \cap +) + P(\overline D \cap -) = \Sexpr{round(tp + tn, 4)}$.
\item Minimum sensitivity to diagnose the disease $P(+|D)=\Sexpr{round(minspe, 4)}$.
\end{enumerate}
\end{solution}


%% META-INFORMATION
%% \extype{num}
%% \exsolution{Solution}
%% \exname{test-10-med}
%% \extol{0.001}
%% \degree{Medicine}
 
  