<<echo=FALSE, results=hide>>=
## DATA GENERATION
fp <- 0.01
fn <- 0.002
pre <- 1 / 400
# Risks
ntd <- 2
nth <- 698
ncd <- 3
nch <- 297
## QUESTION/ANSWER GENERATION
sen <- 1 - fn / pre
spe <- 1 - fp / (1 - pre)
tp <- pre * sen
tn <- (1 - pre) * spe
ppv <- tp / (tp + fp)
npv <- tn / (tn + fn)
# Risks
nt <- ntd + nth
nc <- ncd + nch
n <- nt + nc
rt <- ntd / nt
rc <- ncd / nc
rr <- rt / rc
ot <- ntd / nth
oc <- ncd / nch
or <- ot / oc
@

\begin{question}
\puntos{3.5} A test to detect prostate cancer produces 1\% of false positives and 0.2\% false negatives. It is known that 1 in 400 males suffer this type of cancer.
\begin{enumerate}
\item Compute the sensitivity and the specificity of the test.
\item If a male got a positive outcome in the test, what is the chance of developing cancer?
\item Compute and interpret the negative predictive value.
\item Is this test better to predict or to rule out the cancer?
\item To study wh ether there is an association between the practice of sports and this type of cancer, a sample of 1000 males was drawn, of which 700 practiced sports, and it was observed that there were 2 males with cancer in the group of males who practiced sports, and there were 3 males with cancer in the group of males who did not practice sports. Compute the relative risk and the odds ratio and interpret them. 
\end{enumerate}
\end{question}

%% SOLUTIONS
\begin{solution}
Let $D$ the event corresponding to suffering prostate cancer and $+$ and $-$ the events corresponding to get a positive and a negative outcome respectively.
\begin{enumerate}
\item The sensitivity is $P(+|D) = \Sexpr{round(sen, 4)}$ and specificity $P(-|\overline D) = \Sexpr{round(spe, 4)}$.
\item Positive predictive value $P(D|+) = \Sexpr{round(ppv, 4)}$.
\item Negative predictive value $P(\overline D|-) = \Sexpr{round(npv, 4)}$. 
\item As the positive predictive value is smaller than the negative predictive value, this test is better to rule out the disease. In fact, we can not use this test to detect the prostate cancer because the positive predictive value is less than 0.5.
\item $RR(D)=\Sexpr{round(rr, 4)}$ and $OR(D)=\Sexpr{round(or, 4)}$. Thus, there is an association between the practice of sports and the prostate cancer and the risks and the odds of developing cancer is almost one fourth smaller if    the male practice sports.
\end{enumerate}
\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{Solution}
%% \exname{test-med-5}
%% \extol{0.001}
%% \degree{Medicine}
 
  