
```{r echo=FALSE, results=hide}
## DATA GENERATION
tp <- 60
fn <- 10
fp <- 80
tn <- 200
n <- tp + fn + fp + tn
pre <- 0.02
## QUESTION/ANSWER GENERATION
sen <- tp / (tp + fn)
spe <- tn / (fp + tn)
ppv <- tp / (tp + fp)
npv <- tn / (tn + fn)
ppv2 <- (pre * sen) / (pre * sen + (1 - pre) * (1 - spe))
npv2 <- ((1 -pre) * spe) / (pre * (1 - sen) + (1 - pre) * spe)
```

Question
========
The table below shows the results of a study to evaluate the usefulness of a reactive strip to diagnose an urinary infection.

$$
\begin{array}{ccc}
\hline
\mbox{Outcome} & \mbox{Infection} & \mbox{No infection}  
\mbox{Positive} & 60 & 80\\
\mbox{Negative} & 10 & 200\\
\hline
\end{array}
$$

a. Compute the sensitivity and the specificity of the test.
a. Compute the positive and the negative predictive values. Is this test better to confirm or to rule out the infection?
a. If another study has determined that the true prevalence of the infection is 2%:, how does this affect to the predictive values?

Solution
========
Let $D$ be the event corresponding to suffering the urinary infection and $+$ and $-$ the events corresponding to get a positive and negative outcome in the test respectively.
a. Sensitivity = $`r round(sen, 4)`$ and Specificity = $`r round(spe, 4)`$.
a. $PPV=`r round(ppv, 4)`$ and $NPV=`r round(npv,4)`$. Since the $PPV<NPV$ the test is better to rule out the infection.
a. $PPV=`r round(ppv2, 4)`$ and $NPV=`r round(npv2,4)`$. The positive predictive value descreases a lot while the negative predictive value increases al little bit.
  
Meta-information 
================
extype: num
exsolution: Solution
exname: test-med-1
extol: 0.001
degree: Medicine
 
