```{r echo=FALSE, results="hide"}
## DATA GENERATION
val <- c(1, 3, 5, 7, 9)
freq <- c(3, 12, 9, 18, 22)
x <- rep(val, freq)

# QUESTION/ANSWER GENERATION
# Tamaño de la muestra
nx <- length(x)
# Media
mx <- mean(x)
my <- 6.8
# Varianza
s2x <- sum(x^2)/nx-mx^2
# Desviación típica
sx <- sqrt(s2x)
sy <- 2.6
# Coef. variación
cvx <- sx/mx
# Coef. asimetría
g1x <- sum((x-mx)^3)/(nx*sx^3)
# Coef. apuntamiento
g2x <- sum((x-mx)^4)/(nx*sx^4)-3
# Puntuaciones típicas
zx = (6 - mx) / sx
zy = (6 - my) / sy
```

Question
========
The patients of a physiotherapy clinic were asked to assess their satisfaction in a scale from 0 to 10. The assessments are summarized in the table below.

$$
\begin{array}{lr} 
\hline
\mbox{Assessment} & \mbox{Patients}  
0 - 2 & 3\\
2 - 4 & 12\\  
4 - 6 & 9\\ 
6 - 8 & 18\\ 
8 - 10 & 22\\ 
\hline
\end{array}
$$


a. Compute the interquartile range of the assessment and interpret it.

a. If it is required an assessment greater than 5 in more than 50% of patients for the clinic to remain open, will the clinic remain open?

a. Is the assessment mean representative?

a. Compute the coefficient of kurtosis of the assessment and interpret it. Is the kurtosis normal?

a. If the assessment mean of another clinic is 6.8 and the standard deviation is 2.6,  which assessment is relatively higher 6 in the first clinic or 6.2 in the second?


Use the following sums for the computations:  
$\sum x_in_i=`r sum(x)`$, $\sum x_i^2n_i=`r sum(x^2)`$, $\sum (x_i-\bar x)^3n_i=`r round(sum((x-mx)^3),2)`$ and $\sum (x_i-\bar x)^4n_i=`r round(sum((x-mx)^4),2)`$.

Solution
========
Let $X$ be the patient assessment.

a. $Q_1= 4.4444$, $Q_3=9.0907$ and $IQR = 4.6463$, so the central dispersion is moderate.

a. $F(5)=0.2695$, and the percentage of patients with an assessment greater than 5 is $73.05%$.

a. $\bar x = `r round(mx, 4)`$, $s_x^2 = `r round(s2x, 4)`$, $s_x=`r round(sx, 4)`$ and $cv=`r round(cvx,4)`$, thus the representativity of the mean is moderate.

a. $g_2 = `r round(g2x, 4)`$ and the distribution is flatter than a Gauss bell, but normal, as $g_2$ is between -2 and 2.

a. First clinic: $z(6)=`r round(zx, 4)`$   
Second clinic: $z(6.2)=`r round(zy, 4)`$.  
Thus, an assessment of 6 in the first clinic is relatively higher as its standard score is greater. 

Meta-information 
================
extype: num
exsolution: Solution
exname: des-24-fis
extol: 0.001
degree: Physiotherapy
 
