
```{r echo=FALSE, results="hide"}
## DATA GENERATION
pA <- 0.9
pB <- 0.7
pNoANoB <- 0.05

## QUESTION/ANSWER GENERATION
pNoA <- 1 - pA
pAB <- 0.65
pANoB <- 0.25
pNoAB <- 0.05
pBSiNoA <- pNoAB / pNoA
pAoB <- 1 - pNoANoB
# Random variables
p1 <- pbinom(3, 6, pA, lower.tail = F)
p2 <- ppois(2, 5)
p3 <- pbinom(2, 5, pAoB, lower.tail = F)
```

Question
========
Two treatments are being tested against Covid-19. Treatment $A$ has an effectiveness of 90 % while treatment $B$ has an effectiveness of 70 %. It has also been found that in 5% of the patients affected by Covid-19 neither of the two treatments is effective.

a. Compute the probability that for a patient with Covid-19 only treatment $A$ is effective.

a. What is the probability that treatment $B$ is effective if $A$ was not effective for a Covid-19 patient?

a. Are independent the two treatments?

a. Compute the probability that in a sample of 6 Covid-19 patients the treatment $A$ is effective in at least 4 of them.

a. Compute the probability that in a sample of 100 Covid-19 patients there are less than 3 where none of the treatments are effective.

a. Compute the probability that in a sample of 5 Covid-19 patients some of the treatments is effective in at least 3 of them.

Solution
========

a. $P(A\cap \overline B) = `r pANoB`$.

a. $P(B|\overline A) = `r pBSiNoA`$.

a. The events are dependent, since $P(B|\overline A)\neq P(B)$.

a. Let $X$ be the number of patients with treatment A effective in a sample of 6. Then $X\sim B(6, 0.9)$ and $P(X\geq 4)=`r round(p1, 4)`$.

a. Let $Y$ be the number of patients with none of the treatments effective in a sample of 100. Then $X\sim B(100, 0.05)\approx P(5)$ and $P(Y<3)=`r round(p2, 4)`$.

a. Let $Z$ be the number of patients with some treatment effective in a sample of 5. Then $Z\sim B(5, 0.95)$ and $P(X\geq 3)=`r round(p3, 4)`$.

Meta-information 
================
extype: num
exsolution: Solution
exname: vad-med-13
extol: 0.001
degree: Medicine
 
