
```{r echo=FALSE, results="hide"}
## DATA GENERATION
n <- 10
p <- 0.05
## QUESTION/ANSWER GENERATION
p1 <- pbinom(1, n, p, lower.tail = F)
min <- log(0.1)/log(0.95)
pbinom(0, 45, p, lower.tail = F)
lambda <- 15
p2 <- dpois(13, lambda)
```

Question
========
The new drug Recalnal for mitigating kidney stones produces side effects in the form of liver damage in 5% of patients taking Recalnal. The drug is administered to 10 patients. 


a. Justify the type of distribution followed by the variable that measures the number of patients with liver damage.

a. What is the probability that at least 2 of them have liver damage?

a. Let $E_n$ be the event that at least one of $n$ patients suffers liver damage when receiving Recalnal. In drug feasibility experiments $P(E_n)$ is used as a criterion about how safe the drug is. What is the minimum value of $n$ such that $P(E_n)>0.9$?

In the experimental phase of Recalnal, an average of 3 doses per minute are administered to volunteers.

d. Justify the type of distribution followed by the variable that measures the number of doses administered every 5 minutes.
e. What is the probability that 13 doses are administered in 5 minutes?

Solution
========


Meta-information 
================
extype: num
exsolution: Solution
exname: vad-16-far
extol: 0.001
degree: Pharmacy
 
