
```{r echo=FALSE, results="hide"}
## DATA GENERATION
library(knitr)
knitr::opts_chunk$set(echo = F, message = F, warning = F)
library(kableExtra)
sumx <- 15.9
sumlogx <- 3.852
sumy <- 41.5
sumlogy <- 11.511
sumx2 <- 42.23
sumlogx2 <- 5.559
sumy2 <- 274.25
sumlogy2 <- 20.742
sumxy <- 103.3
sumxlogy <- 28.047
sumlogxy <- 32.616
n <- 8

## QUESTION/ANSWER GENERATION
# means
mx <- sumx/n
mlogx <- sumlogx/n
my <- sumy/n
mlogy <- sumlogy/n
# variances
s2x <- sumx2/n-mx^2
s2logx <- sumlogx2/n-mlogx^2
s2y <- sumy2/n-my^2
s2logy <- sumlogy2/n-mlogy^2
# Covariances
sxlogy <- sumxlogy/n-mx*mlogy
slogxy <- sumlogxy/n-mlogx*my
# Deterhoursation coeff
r2xlogy <- sxlogy^2/(s2x*s2logy)
r2logxy <- slogxy^2/(s2logx*s2y)
# Exponential regression model
aexp <- mlogy - sxlogy/s2x*mx
bexp <- sxlogy/s2x
# Logarithmic regression model
alog <- my - slogxy/s2logx*mlogx
blog <- slogxy/s2logx
# Prediction
y0 <- alog+blog*3.2
```

Question
========
We have measured the average number of weekly hours of study $X$ and the score in a clinic entrance test $Y$ of 8 candidates, getting the following results:

$\sum x_i=`r sumx`$, $\sum \log(x_i)=`r sumlogx`$, $\sum y_j=`r sumy`$, $\sum \log(y_j)=`r sumlogy`$,  
$\sum x_i^2=`r sumx2`$, $\sum \log(x_i)^2=`r sumlogx2`$, $\sum y_j^2=`r sumy2`$, $\sum \log(y_j)^2=`r sumlogy2`$,  
$\sum x_iy_j=`r sumxy`$, $\sum x_i\log(y_j)=`r sumxlogy`$, $\sum \log(x_i)y_j=`r sumlogxy`$.


a. Compute the equations of the logarithmic and exponential regression models of the score as a function of the average number of hours of study.

a. Use the best of the previous models to predict the score for somebody that study $3.2$ hours a week. Is this prediction reliable?

Solution
========


a. $\bar x=`r round(mx,4)`$ hours, $s_x^2=`r round(s2x,4)`$ hours$^2$.  
$\overline{\log(x)}=`r round(mlogx,4)`$ log(hours), $s_{\log(x)}^2=`r round(s2logx,4)`$ log(hours)$^2$.  
$\bar y=`r round(my,4)`$ points, $s_y^2=`r round(s2y,4)`$ points$^2$.  
$\overline{\log(y)}=`r round(mlogy,4)`$ log(points), $s_{\log(y)}^2=`r round(s2logy,4)`$ log(points)$^2$.  
$s_{x\log(y)}=`r round(sxlogy,4)`$, $s_{\log(x)y}=`r round(slogxy,4)`$  
Logarithmic regression model: $y=`r round(alog,4)`+`r round(blog,4)`\log(x)$  
Exponential regression model: $y=e^{`r round(aexp,4)`+`r round(bexp,4)`x}$

a. Logarithmic coefficient of determination: $r^2=`r round(r2logxy,4)`$  
Exponential coefficient of determination: $r^2=`r round(r2xlogy,4)`$  
Therefore, the best regression model to predict is the exponential.  
Prediction: $y(3.2)=`r round(y0,4)`$.

Meta-information 
================
extype: num
exsolution: Solution
exname: regnol-fis-3
extol: 0.001
degree: Physiotherapy
 
