
```{r echo=FALSE, results=hide}
## DATA GENERATION
set.seed(12)
x <- round(runif(40, 20, 45))
y <- 38 + x/20 + round(rnorm(40),1)

## QUESTION/ANSWER GENERATION
# colors
col1 <- "#05A1E6"
# sample size
n <- length(x)
# means
mx <- mean(x)
mlogx <- mean(log(x))
my <- mean(y)
mlogy <- mean(log(y))
# variances
s2x <- sum(x^2)/n-mx^2
s2logx <- sum(log(x)^2)/n-mlogx^2
s2y <- sum(y^2)/n-my^2
s2logy <- sum(log(y)^2)/n-mlogy^2
# Covariances
sxy <- sum(x * y) / n - mx * my
sxlogy <- sum(x*log(y))/n-mx*mlogy
slogxy <- sum(log(x)*y)/n-mlogx*my
# Determination coeff
r2xy <-  sxy^2 / (s2x * s2y)
r2xlogy <- sxlogy^2/(s2x*s2logy)
r2logxy <- slogxy^2/(s2logx*s2y)
# Linear regression model
reglin <- lm(y ~ x)
# Exponential regression model y on x
regexp <- lm(log(x)~y)
# Logarithmic regression model x on y
reglog <- lm(y~log(x))
```

Question
========
A study tries to determine if there is a relation between the gestation time (in weeks) and the age of the mother (in years). A sample of 40 mothers was taken and the sums below summarize the results ($X$=Age and $Y$=Gestation time):

$\sum x_i=`r round(sum(x), 4)`$ years, $\sum \log(x_i)=`r round(sum(log(x)), 4)`$ log(years), $\sum y_j=`r round(sum(y), 4)`$ weeks, $\sum \log(y_j)=`r round(sum(log(y)), 4)`$ log(weeks),  
$\sum x_i^2=`r round(sum(x^2), 4)`$ years$^2$, $\sum \log(x_i)^2=`r round(sum(log(x)^2), 4)`$ log(years)$^2$, $\sum y_j^2=`r round(sum(y^2), 4)`$ weeks$^2$, $\sum \log(y_j)^2=`r round(sum(log(y)^2), 4)`$ log(weeks)$^2$,  
$\sum x_iy_j=`r round(sum(x*y), 4)`$ years$\cdot$weeks, $\sum x_i\log(y_j)=`r round(sum(x*log(y)), 4)`$ years$\cdot$log(weeks), $\sum \log(x_i)y_j=`r round(sum(log(x)*y), 4)`$ log(years)$\cdot$weeks, $\sum \log(x_i)\log(y_j)=`r round(sum(log(x)*log(y)), 4)`$ log(years)$\cdot$log(weeks).

a. Which regression models, linear, exponential or logarithmic, explains better the relation between the age and the gestation time? 
a. Use the best model to predict the gestation time for a mother 45 years old. Is this prediction reliable?
a. According to the linear model, how much increases or decreases the gestation time for every year of the mother?

Solution
========
a. $\overline{x}=`r round(mx,4)`$ weeks, $s_x^2=`r round(s2x,4)`$ weeks$^2$.  
$\bar y=`r round(my,4)`$ Kg, $s_y^2=`r round(s2y,4)`$ Kg$^2$.  
$s_{xy}=`r round(sxy,4)`$ weeks$$\cdot$$Kg.  
Regression coefficient of $Y$ on $X$: $b_{yx} = `r round(reglin$coefficients[2], 4)`$ Kg/week. The grip strength increases $`r round(reglin$coefficients[2], 4)`$ Kg per week.
a. $\overline{\ln(x)} = `r round(mlogx, 4)`$ ln(weeks), $s_{\ln(x)}^2 = `r round(s2logx, 4)`$  ln(weeks)$^2$ and $s_{\ln(x)y} = `r round(slogxy, 4)`$ ln(weeks)Kg.  
Logarithmic regression model of $Y$ on $X$: $y = `r round(reglog$coefficients[1], 4)` + `r round(reglog$coefficients[2], 4)` \ln(x)$.  
Predictions: $y(5) = `r round(reglog$coefficients[1] + reglog$coefficients[2] * log(5), 4)`$ Kg and $y(25) = `r round(reglog$coefficients[1] + reglog$coefficients[2] * log(25), 4)`$ Kg.  
Logarithmic coefficient of determination: $r^2 = `r round(r2logxy, 4)`$.
The predictions are not reliable because the sample size is small.  
Linear coefficient of determination: $r^2 = `r round(r2xy, 4)`$.  
As the linear coefficient of determination is less than the logarithmic one, the predictions with the logarithmic model are more reliable.
a. Exponential regression model of $X$ on $Y$: $x = e^{`r round(regexp$coefficients[1],4)` + `r round(regexp$coefficients[2],4)`y}$.  
Prediction: $x(25)=`r round(exp(regexp$coefficients[1] + regexp$coefficients[2]*25), 4)`$ Weeks.  
a. As $r^2 = `r round(r2logxy, 4)`$, the exponential models explains $`r round(r2logxy, 4) * 100`$%: of the variabilidty of the weeks.

Meta-information 
================
extype: string
exsolution: Solution
exname: regnol-15-gen
extol: 0.001
degree: All
 
