
```{r echo=FALSE, results=hide}
## DATA GENERATION
pC <- 0.3
pCyF <- 0.2
pCSiF <- 0.5

## QUESTION/ANSWER GENERATION
pF <- pCyF/pCSiF
pCoF <- pC + pF - pCyF
pCyNoF <- pC - pCyF
pNoCyF <- pF - pCyF
pNoCyNoF <- 1 - pCoF
```

Question
========
	
Two symptoms of COVID-19 are fever and cough. We know that 30%: of people with COVID-19 cough and 20%: have fever and cough. Also, if somebody with COVID-19 have fever then the probability of coughing 0.5.

a. Construct the probability tree for the sample space of the random experiment consisting in picking a random person with COVID-19 and measuring the symptoms that he or she have.
a. Calculate the probability of having any of the symptoms.
a. Calculate the probability of having only cough.
a. Calculate the probability of having only fever.
a. Calculate the probability no fever nor cough.
a. Are the symptoms dependent or independent?

Solution
========
Let $C$ and $F$ be the events of having cough and fever respectively. According to the statement $P(C)=`r round(pC, 4)`$, $P(C\cap F)=`r round(pCyF, 4)`$ and $P(C|F)=`r pCSiF`$.
a. $P(C\cup F) = `r round(pCoF, 4)`$.
a. $P(C\cap \overline F) = `r round(pCyNoF, 4)`$.
a. $P(\overline C \cap F) = `r round(pNoCyF, 4)`$.
a. $P(\overline C \cap \overline F) = `r round(pNoCyNoF, 4)`$.
a. The events are dependent since $P(C)\neq P(C|F)$.

Meta-information 
================
extype: num
exsolution: Solution
exname: prob-med-8
extol: 0.001
degree: Medicine
 
