<<echo=FALSE, results=hide>>=
## DATA GENERATION
pB <- 0.4
pV <- 0.4
pVsiB <- 0.8
pNoBNoV <- 0.52

## QUESTION/ANSWER GENERATION
pVB <- pB * pVsiB
pBsiV <- pVB / pV
pVnoB <- pV - pVB
@

\begin{question}
\puntos{2}An organism has the same chance of being infected by a virus and a bacteria. At the same time, the probability of being infected by a virus doubles when the organism has been previously infected by a bacteria. On the other hand, the probability of being infected by no pathogen (neither virus nor bacteria) is $0.52$.
\begin{enumerate}
\item What is the probability of being infected by a virus and a bacteria at the same time?
\item What is the probability of being infected by a bacteria if it has been infected by a virus?
\item What is the probability of being infected only by a virus?
\item Are the events of being infected by a virus an a bacteria independent?
\end{enumerate}
\end{question}


%% SOLUTIONS
\begin{solution}
Let $V$ and $B$ the events corresponding to be infected by a virus and a bacteria respectively.
\begin{enumerate}
\item $P(V\cap B) = \Sexpr{round(pVB, 4)}$.
\item $P(B|V) = \Sexpr{round(pBsiV, 4)}$.
\item $P(V\cap \overline B) = \Sexpr{round(pVnoB, 4)}$.
\item The events are dependents since $P(V) = \Sexpr{round(pV, 4)} \neq \Sexpr{round(pVsiB, 4)} = P(V|B)$.
\end{enumerate}
\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{Solution}
%% \exname{prob-med-9}
%% \extol{0.001}
%% \degree{Medicine}
 
