
```{r echo=FALSE, results="hide"}
## DATA GENERATION
pA <- 1/15
pB <- 0.05
pAB <- pA * pB 

## QUESTION/ANSWER GENERATION
pAoB <- pA + pB - pAB 
pAnoB <- pA - pAB
pnoAnoB <- 1 - pAoB
pAsiB <- pAB / pB
```

Question
========
Respiratory allergies affect 1 out of every 15 individuals in a population, while food intolerances affect 5% of individuals. Assuming that the two problems are independent, 

a. Compute the probability of having at least one of the problems.

a. Compute the probability of having an allergy but not an intolerance.

a. Compute the probability of having neither of the two problems.

a. Compute the probability of having an allergy if you have an intolerance.

Solution
========

Let $A$ the event of having respiratory allergies and $B$ the event of having food intolerance.

a. $P(A\cup B) = `r round(pAoB,4)`$.

a. $P(A-B) = `r round(pAnoB,4)`$.

a. $P(\overline A  \cap \overline B) = `r round(pnoAnoB, 4)`$.

a. $P(A|B) = `r round(pAsiB, 4)`$.

Meta-information 
================
extype: string
exsolution: Solution
exname: prob-14-med
extol: 0.001
degree: Medicine
 
