
```{r echo=FALSE, results="hide"}
## DATA GENERATION
A <- 40
B <- 50
C <- 60
pA <- A/(A + B + C)
pB <- B/(A + B + C)
pC <- C/(A + B + C)
pRSiA <- 0.8
pRSiB <- 0.82
pRSiC <- 0.78

## QUESTION/ANSWER GENERATION
pNoRSiA <- 1 - pRSiA 
pNoRSiB <- 1 - pRSiB
pNoRSiC <- 1 - pRSiC
pNoR <- pA * pNoRSiA + pB * pNoRSiB + pC * pNoRSiC
pR <- 1 - pNoR
pBSiNoR <- pB * pNoRSiB / pNoR
pASiR <- pA * pRSiA / pR
pBSiR <- pB * pRSiB / pR
pCSiR <- pC * pRSiC / pR
```

Question
========
	
A hospital orders a DNA compatibility test to three labs A, B and C. Lab A performs 40 test a day, lab B 50, and lab C 60. It is known that the probability of a wrong diagnose is 20% in lab A, 18% in lab B and 22% in lab C. If we select a random test of the hospital,


a. Compute the probability of wrong diagnose in that test.

a. If the test is wrong, what is the probability that it has been performed by lab B?

a. If the test is right, which lab is more likely to have performed the test?

Solution
========
Let $A$, $B$ and $C$ be the events of performing the test in labs $A$, $B$ and $C$ respectively, and $R$ the event of getting a right diagnose. According to the statement $P(A)=`r round(pA, 4)`$, $P(B)=`r round(pB, 4)`$, $P(C)=`r round(pC, 4)`$, $P(R|A)=`r pRSiA`$, $P(R|B)=`r pRSiB`$ and $P(R|C)=`r pRSiC`$.

a. $P(\overline R) = `r round(pNoR, 4)`$.

a. $P(B|\overline R) = `r round(pBSiNoR, 4)`$.

a. $P(A|R) = `r round(pASiR, 4)`$, $P(B|R) = `r round(pBSiR, 4)`$ and $P(C|R) = `r round(pCSiR, 4)`$, thus, it is more likely that it has been performed in lab $C$.

Meta-information 
================
extype: num
exsolution: Solution
exname: prob-med-7
extol: 0.001
degree: Medicine
 
