
```{r echo=FALSE, results="hide"}
## DATA GENERATION
x <- c(175, 182, 190, 165, 172, 183, 187, 174, 168, 178)
y <- c(164, 175, 165, 160, 155, 172, 160, 151, 165, 163)
z <- c(177, 180, 193, 172, 173, 188, 185, 177, 168, 182)
sumx <- sum(x)
sumy <- sum(y)
sumz <- sum(z)
sumx2 <- sum(x^2)
sumy2 <- sum(y^2)
sumz2 <- sum(z^2)
sumxy <- sum(x*y)
sumxz <- sum(x*z)
sumyz <- sum(y*z)
n <- length(x)
  
## QUESTION/ANSWER GENERATION
# means
mx <- sumx / n
my <- sumy / n
mz <- sumz / n
# variances
s2x <- sumx2/n-mx^2
s2y <- sumy2/n-my^2
s2z <- sumz2/n-mz^2
# Covariances
sxz <- sumxz/n-mx*mz
syz <- sumyz/n-my*mz
# Detercmation coeff
r2xz <- sxz^2/(s2x*s2z)
r2yz <- syz^2/(s2y*s2z)
  # Slopes
  bzx <- sxz/s2x
  bzy <- syz/s2y
  # Intercept
  azx <- mz - bzx * mx
  # Prediction
  predz <- azx + bzx * 181
```

Question
========
In a sample of 10 families with a son older than 20 it has been measured the height of the father ($X$), the mother ($Y$) and the son ($Z$) in centimetres, getting the following results:

$\sum x_i=`r sumx`$ cm, $\sum y_i=`r sumy`$ cm, $\sum z_i=`r sumz`$ cm,  
$\sum x_i^2=`r sumx2`$ cm$^2$, $\sum y_i^2=`r sumy2`$ cm$^2$, $\sum z_i^2=`r sumz2`$ cm$^2$,  
$\sum x_iy_j=`r sumxy`$ cm$^2$, $\sum x_iz_j=`r sumxz`$ cm$^2$, $\sum y_iz_j=`r sumyz`$ cm$^2$.


a. On which height does the height of the son depend more linearly, the height of the father or the mother?

a. Using the best linear regression model, predict the height of a son with a father 181 cm tall and a mother 163 cm tall.

a. According to the linear model, how much the height of the son will increase for each centimetre that increases the height of the father? And for each centimetre that increases the height of the mother?

a. How would the reliability of the prediction be if the heights were measured in inches? (An inch is 2.54 cm).
\end{enumerate} 

Solution
========

a. $\bar x=`r round(mx,4)`$ cm, $s_x^2=`r round(s2x,4)`$ cm$^2$,  
$\bar y=`r round(my,4)`$ cm, $s_y^2=`r round(s2y,4)`$ cm$^2$,  
$\bar z=`r round(mz,4)`$ cm, $s_z^2=`r round(s2z,4)`$ cm$^2$,  
$s_{xz}=`r round(sxz,4)`$ cm$^2$ and $s_{yz}=`r round(syz,4)`$ cm$^2$.  
$r^2_{xz}=`r round(r2xz,4)`$ and $r^2_{yz}=`r round(r2yz,4)`$, thus the height of the son depends linearly more on the height of the father since the $r^2_{xz}>r^2_{yz}$.

a. Regression line of $Z$ on $X$: $z=`r round(azx,4)` + `r round(bzx,4)`x$ and $z(181)=`r round(predz, 4)`$.

a. The height of the son will increase $`r round(bzx,4)`$ cm per cm of the height of the father and $`r round(bzy,4)`$ cm per cm of the height of the mother.

a. The reliability of the prediction will be the same, as after applying the same linear transformation to $X$ and $Z$, the variances are multiplied by the square of the slope and the covariance is also multiplied by de square of the slope.

Meta-information 
================
extype: num
exsolution: Solution
exname: reglin-far-11
extol: 0.001
degree: Pharmacy
 
