
```{r echo=FALSE, results=hide}
## DATA GENERATION
x1 <- 230
p1 <- 1 - 3420 / 10000
x2 <- 210
p2 <- 1 - (4936 + 3420) / 10000
x3 <- 230
p3 <- 1 - 1234 / 10000

## QUESTION/ANSWER GENERATION
q1 <- qnorm(p1)
q2 <- qnorm(p2)
q3 <- qnorm(p3)
# Define the matrices for the system of equations
A <- matrix(c(1, 1, q1, q2), nrow = 2)
B <- matrix(c(x1, x2), nrow = 2)
X <- solve(A, B)
meanx <- X[1]
sd <- X[2]
meany <- x3 - q3 * sd 
p <- pnorm(240, meanx, sd) - pnorm(200, meanx, sd)
iqr <- qnorm(0.75, meany, sd) - qnorm(0.25, meany, sd)
```

Question
========
In a study about the cholesterol two samples of 10000 males and 10000 females was taken. It was observed that 3420 males and 1234 females had a cholesterol level above 230 mg/dl, and that 4936 males had a cholesterol level between 210 and 230 mg/dl. 
Assuming that the cholesterol level in males and females follows a normal distribution with the same standard deviation, compute:

a. The means and the standard deviation of the distributions of cholesterol level in males and females.
a. The percentage of males with cholesterol level between 200 and 240 mg/dl.
a. The interquartile range of the cholesterol level of females.

Solution
========
a. Let $X$ be cholesterol level in males and $Y$ the cholesterol level in females, then $X\sim N(`r round(meanx, 4)`, `r round(sd, 4)`)$ and $X\sim N(`r round(meany, 4)`, `r round(sd, 4)`)$
a. $P(200\leq X \leq 240) = `r round(p, 4)`$.
a. $IQR = `r round(iqr, 4)`$ mg/dl.

Meta-information 
================
extype: num
exsolution: Solution
exname: vac-med-8
extol: 0.001
degree: Pharmacy
 
