
```{r echo=FALSE, results=hide}
## DATA GENERATION
mx <- 5
sx <- 2
my <- 25
sy <- 5
pre <- 0.005
## QUESTION/ANSWER GENERATION
p1 <- pnorm(20, my, sy) - pnorm(15, my, sy)
p99 <- qnorm(0.01, mx, sx, lower.tail = F)
sen <- pnorm(12, my, sy, lower.tail = F)
spe <- pnorm(12, mx, sx)
fn <- (1 - sen) * pre
fp <- (1 - spe) * (1 - pre)
```

Question
========
A study tries to determine the effect of a low fat diet in the lifetime of rats. The rats where divided into two groups, one with a normal diet and another with a low fat diet. It is assumed that the lifetimes of both groups are normally distributed with the same variance but different mean. If 20%: of rats with normal diet lived more than 12 months, 5%: less than 8 months, and 85%: of rats with low fat diet lived more than 11 months,

a. What is the mean and the standard deviation of the lifetime of rats following a low fat diet?
a. If 40%: of the rats were under a normal diet, and 60%: of rats under a low fat diet, what is the probability that a random rat die before 9 months?

Solution
========


Meta-information 
================
extype: num
exsolution: Solution
exname: vac-med-13
extol: 0.001
degree: Medicine
 
  
