
```{r echo=FALSE, results=hide}
## DATA GENERATION
m1 <- 26
s1 <- 2.1
m2 <- 15
s2 <- 2.8
x1 <- 22
pre <- 0.06
n1 <- 10
x2 <- 8
n2 <- 70
x3 <- 2
x4 <- 5
## QUESTION/ANSWER GENERATION
sen <- pnorm(x1, m1, s1, lower.tail = F)
spe <- pnorm(x1, m2, s2)
tp <- pre*sen
fn <- pre*(1-sen)
fp <- (1-pre)*(1-spe)
tn <- (1-pre)*spe
ppv <- tp/(tp+fp)
npv <- tn/(tn+fn)
p <- tp+fp
p1 <- pbinom(x2,n1,ppv,lower.tail = F)
lambda <- n2*p
p2 <- ppois(x4,lambda)-ppois(x3-1,lambda)
```

Question
========
It is known that eye pressure in patients with glaucoma follows a normal distributions with mean $`r m1`$ mmHg and standard deviation $`r s1`$ mmHg, while in people without glaucoma follows a normal distribution with mean $`r m2`$ mmHg and standard deviation $`r s2`$ mmHg.
A test for detecting glaucoma gives a positive outcome when the eye pressure is above `r x1` mmHg and a negative outcome if not. 

a. Compute the sensitivity and the specificity of the test.  
**Remark**: If you are not able to compute this values, assume a sensitivity of $0.95$ and a specificity of $0.97$ for the following parts.
a. If there are `r pre*100`%: of persons with glaucoma in the population, what are the positive and negative predictive values of the test?
a. If we consider `r n1` persons with a positive outcome in the test, what is the probability that more than `r x2` suffer glaucoma?
a. If we apply the test to `r n2` persons, what is the probability of getting between `r x3` and `r x4` positive outcomes, both included?

Solution
========
a. Let $X_1$ the eye pressure in patients with glaucoma and $X_2$ in people without glaucoma.  
Sensitivity: $P(+|D)=P(X_1>22)=`r round(sen,4)`$.  
Specificity: $P(-|\overline{D})=P(X_2\leq 22)=`r round(spe,4)`$.
a. $PPV=P(D|+)=`r round(ppv,4)`$ and $NPV=P(\overline D|-)=`r round(npv,4)`$.
a. Let $Y$ be the number of persons with glaucoma in a sample of 10 persons with a positive outcome in the test. $Y\sim B(`r n1`,`r round(ppv,4)`)$ and $P(Y>`r x2`)=`r round(p1,4)`$.
a. Let $U$ be the numer of persons with a positive outcome in the test in a sample of 70 persons. $U\sim B(`r n2`,`r round(p,4)`)\approx P(`r round(lambda,4)`)$ and $P(`r x3`\leq U\leq `r x4`)=`r round(p2,4)`$.

Meta-information 
================
extype: num
exsolution: Solution
exname: vac-opt-2
extol: 0.001
degree: Optics
 
