
```{r echo=FALSE, results=hide}
## DATA GENERATION
x1 <- 45
p1 <- 1 - 0.15
x2 <- 30
p2 <- 0.03
n <- 5

## QUESTION/ANSWER GENERATION
q1 <- qnorm(p1)
q2 <- qnorm(p2)
# Define the matrices for the system of equations
A <- matrix(c(1, 1, q1, q2), nrow = 2)
B <- matrix(c(x1, x2), nrow = 2)
X <- solve(A, B)
mean <- X[1]
sd <- X[2]
p <- pnorm(50, mean, sd, lower.tail = F)
p3 <- pbinom(0, n, p, lower.tail = F)
```

Question
========
It is known that the annual rainfall in a region follows a normal probability distribution.
If the statistics show that 15%: of the years the annual rainfall has been greater than 45 cm and 3%: of the years less than 30 cm,

a. Compute the mean and the stantdard deviation of the annual rainfall.  
**Remark**: Use $\mu=40$ cm y $\sigma=3$ cm for the next part if you do not know how to compute them.  
a. What is the probability that in the next 5 years at least one year the annual rainfall was above 50 cm? 

Solution
========
a. Let $X$ be the annual rainfall. $X\sim N(\mu, \sigma)$, and according to the statement $P(X>`r x1`)=`r 1-p1`$ and $P(X<`r x2`)=`r p2`$.  
$\mu=`r round(mean, 4)`$ cm and $\sigma=`r round(sd, 4)`$ cm.
a. Let $Y$ be the number of years in the next 5 years with annual rainfall above 50 cm. Then $Y\sim B(`r n`, `r round(p, 4)`)$, and $P(X\geq 1)=`r round(p3, 4)`$.

Meta-information 
================
extype: num
exsolution: Solution
exname: vac-opt-2
extol: 0.001
degree: Optics
 
